# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6878fffbe033293796db02e2197066246d307285c544e722a5021891d4f387a0227eba4e5732578c56af8e8b743880a9d3c8cda0060f63680f35919688e2ac62

test:
  secret_key_base: 8f226f84a9043c3ede69acd4664eca9a980c0f3d62d122f250faaa334a6013f2dc8b8c26b85618d3c4458974b3990a91e9981e3edf3bee9b6701a51690bdcbbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
